import type {
  ResonanceFieldSample,
  ResonanceGameState,
  ResonanceObstacle,
  ResonanceVector,
} from "./resonance-types";
import {
  RESONANCE_EPSILON as EPSILON,
  add,
  magnitude,
  normalize,
  scale,
  subtract,
  vector,
} from "./resonance-vector";

function orientation(
  first: Readonly<ResonanceVector>,
  second: Readonly<ResonanceVector>,
  third: Readonly<ResonanceVector>,
): number {
  return (second.x - first.x) * (third.y - first.y)
    - (second.y - first.y) * (third.x - first.x);
}

function pointOnSegment(
  start: Readonly<ResonanceVector>,
  end: Readonly<ResonanceVector>,
  point: Readonly<ResonanceVector>,
): boolean {
  return point.x >= Math.min(start.x, end.x) - EPSILON
    && point.x <= Math.max(start.x, end.x) + EPSILON
    && point.y >= Math.min(start.y, end.y) - EPSILON
    && point.y <= Math.max(start.y, end.y) + EPSILON;
}

function segmentsIntersect(
  firstStart: Readonly<ResonanceVector>,
  firstEnd: Readonly<ResonanceVector>,
  secondStart: Readonly<ResonanceVector>,
  secondEnd: Readonly<ResonanceVector>,
): boolean {
  const firstOrientation = orientation(firstStart, firstEnd, secondStart);
  const secondOrientation = orientation(firstStart, firstEnd, secondEnd);
  const thirdOrientation = orientation(secondStart, secondEnd, firstStart);
  const fourthOrientation = orientation(secondStart, secondEnd, firstEnd);
  const firstCrosses = (firstOrientation > EPSILON && secondOrientation < -EPSILON)
    || (firstOrientation < -EPSILON && secondOrientation > EPSILON);
  const secondCrosses = (thirdOrientation > EPSILON && fourthOrientation < -EPSILON)
    || (thirdOrientation < -EPSILON && fourthOrientation > EPSILON);
  if (firstCrosses && secondCrosses) return true;
  if (Math.abs(firstOrientation) <= EPSILON
    && pointOnSegment(firstStart, firstEnd, secondStart)) return true;
  if (Math.abs(secondOrientation) <= EPSILON
    && pointOnSegment(firstStart, firstEnd, secondEnd)) return true;
  if (Math.abs(thirdOrientation) <= EPSILON
    && pointOnSegment(secondStart, secondEnd, firstStart)) return true;
  return Math.abs(fourthOrientation) <= EPSILON
    && pointOnSegment(secondStart, secondEnd, firstEnd);
}

function segmentIntersectsObstacle(
  start: Readonly<ResonanceVector>,
  end: Readonly<ResonanceVector>,
  obstacle: Readonly<ResonanceObstacle>,
): boolean {
  const startsInside = start.x >= obstacle.x
    && start.x <= obstacle.x + obstacle.width
    && start.y >= obstacle.y
    && start.y <= obstacle.y + obstacle.height;
  if (startsInside) return false;
  const corners = [
    vector(obstacle.x, obstacle.y),
    vector(obstacle.x + obstacle.width, obstacle.y),
    vector(obstacle.x + obstacle.width, obstacle.y + obstacle.height),
    vector(obstacle.x, obstacle.y + obstacle.height),
  ];
  for (let index = 0; index < corners.length; index += 1) {
    const edgeStart = corners[index]!;
    const edgeEnd = corners[(index + 1) % corners.length]!;
    if (segmentsIntersect(start, end, edgeStart, edgeEnd)) return true;
  }
  return false;
}

export function resonanceAcousticTransmission(
  state: Readonly<ResonanceGameState>,
  origin: Readonly<ResonanceVector>,
  sample: Readonly<ResonanceVector>,
): number {
  return state.level.obstacles.reduce((transmission, obstacle) => (
    segmentIntersectsObstacle(origin, sample, obstacle)
      ? transmission * (obstacle.acousticTransmission ?? 0.2)
      : transmission
  ), 1);
}

/** Sample only the deterministic visualization field generated by active pulses. */
export function sampleResonanceField(
  state: Readonly<ResonanceGameState>,
  position: Readonly<ResonanceVector>,
): ResonanceFieldSample {
  if (!Number.isFinite(position.x) || !Number.isFinite(position.y)) {
    throw new RangeError("Resonance field sample coordinates must be finite.");
  }
  let pressure = 0;
  let intensity = 0;
  let gradient = vector(0, 0);
  let contributingPulses = 0;
  for (const pulse of state.wavePulses) {
    const offset = subtract(position, pulse.origin);
    const shellOffset = magnitude(offset) - pulse.radius;
    const normalizedOffset = shellOffset / state.options.waveShellWidth;
    if (Math.abs(normalizedOffset) > 3) continue;
    const envelope = Math.exp(-0.5 * normalizedOffset * normalizedOffset);
    const signedWave = Math.cos(normalizedOffset * Math.PI) * envelope;
    const transmitted = resonanceAcousticTransmission(state, pulse.origin, position);
    const contribution = pulse.amplitude * signedWave * transmitted;
    pressure += contribution;
    intensity += Math.abs(contribution);
    gradient = add(
      gradient,
      scale(
        normalize(offset, vector(0, 0)),
        -pulse.amplitude * normalizedOffset * envelope * transmitted,
      ),
    );
    contributingPulses += 1;
  }
  return { pressure, intensity, gradient, contributingPulses };
}
